# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  whiteboard

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
Resources:

  BoardMessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: board-messages-table
        AttributeDefinitions:
          - AttributeName: partKey
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        KeySchema:
          - AttributeName: partKey
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

BoardHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Test
      CorsConfiguration: True

PostMessageFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: src/handlers/postMessage.handler
        Runtime: nodejs12.x
        MemorySize: 128
        Timeout: 5
        Events:
          PostMessage:
            Type: HttpApi
            Properties:
              ApiId: !Ref BoardHttpApi
              Method: POST
              Path: /messages
        Policies:
          - AmazonDynamoDBFullAccess

GetMessagesFunction:
        Type: AWS::Serverless::Function
        Properties:
          Handler: src/handlers/getMessages.handler
          Runtime: nodejs12.x
          MemorySize: 128
          Timeout: 5
          Events:
            GetMessages:
              Type: HttpApi
              Properties:
                ApiId: !Ref BoardHttpApi
                Method: GET
                Path: /messages
          Policies:
            - AmazonDynamoDBFullAccess